Makefile: Add missing ndctl dependency to "release" target
make release fails with error on a fresh clone.

The "release" target was missing ndctl as a dependency, causing link
errors when doing "make release" directly on a fresh clone:

error:  undefined reference to `daxctl_dev_enable_famfs'

The "debug" target correctly had ndctl as a dependency, so,
doing "make debug" first and then "make release" did not hit the issue.

Signed-off-by: Aravind Ramesh <arramesh@micron.com>